# Understanding Global Climate Change
This project analyzes global temperature trends from 2000 to 2015 and builds interactive visualizations to explore patterns, uncertainties, and regional differences.

In [1]:
%pip install pandas numpy plotly dash

Requirement already satisfied: pandas in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (2.2.3)
Requirement already satisfied: numpy in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (2.2.5)
Requirement already satisfied: plotly in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (6.0.1)
Requirement already satisfied: dash in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (3.0.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2025.2)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from plotly) (1.36.0)
Requirement already satisfied: packaging in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from plotly) (25.0)
Requirement already satisfied: Flask<3.1,>=1.0.4 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dash) (3.0.3)
Requirement already satisfied: Werkzeug<3.1 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dash) (3.0.6)
Requirement already satisfied: importlib-metadata in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dash) (8.7.0)
Requirement already satisfied: typing-extensions>=4.1.1 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dash) (4.13.2)
Requirement already satisfied: requests in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dash) (2.32.3)
Requirement already satisfied: retrying in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dash) (1.3.4)
Requirement already satisfied: nest-asyncio in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dash) (1.6.0)
Requirement already satisfied: setuptools in c:\program files\windowsapps\pythonsoftwarefoundation.python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\lib\site-packages (from dash) (65.5.0)
Requirement already satisfied: Jinja2>=3.1.2 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from Flask<3.1,>=1.0.4->dash) (3.1.6)
Requirement already satisfied: itsdangerous>=2.1.2 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from Flask<3.1,>=1.0.4->dash) (2.2.0)
Requirement already satisfied: click>=8.1.3 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from Flask<3.1,>=1.0.4->dash) (8.1.8)
Requirement already satisfied: blinker>=1.6.2 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from Flask<3.1,>=1.0.4->dash) (1.9.0)
Requirement already satisfied: six>=1.5 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from Werkzeug<3.1->dash) (3.0.2)
Requirement already satisfied: zipp>=3.20 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from importlib-metadata->dash) (3.21.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests->dash) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests->dash) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests->dash) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests->dash) (2025.4.26)
Requirement already satisfied: colorama in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from click>=8.1.3->Flask<3.1,>=1.0.4->dash) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 25.1
[notice] To update, run: C:\Users\srira\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [2]:
%pip install jupyter_dash

Requirement already satisfied: jupyter_dash in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (0.4.2)
Requirement already satisfied: dash in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from jupyter_dash) (3.0.4)
Requirement already satisfied: requests in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from jupyter_dash) (2.32.3)
Requirement already satisfied: flask in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from jupyter_dash) (3.0.3)
Requirement already satisfied: retrying in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from jupyter_dash) (1.3.4)
Requirement already satisfied: ipython in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from jupyter_dash) (9.2.0)
Requirement already satisfied: ipykernel in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from jupyter_dash) (6.29.5)
Requirement already satisfied: ansi2html in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from jupyter_dash) (1.9.2)
Requirement already satisfied: nest-asyncio in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from jupyter_dash) (1.6.0)
Requirement already satisfied: Werkzeug<3.1 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dash->jupyter_dash) (3.0.6)
Requirement already satisfied: plotly>=5.0.0 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dash->jupyter_dash) (6.0.1)
Requirement already satisfied: importlib-metadata in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dash->jupyter_dash) (8.7.0)
Requirement already satisfied: typing-extensions>=4.1.1 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dash->jupyter_dash) (4.13.2)
Requirement already satisfied: setuptools in c:\program files\windowsapps\pythonsoftwarefoundation.python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\lib\site-packages (from dash->jupyter_dash) (65.5.0)
Requirement already satisfied: Jinja2>=3.1.2 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from flask->jupyter_dash) (3.1.6)
Requirement already satisfied: itsdangerous>=2.1.2 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from flask->jupyter_dash) (2.2.0)
Requirement already satisfied: click>=8.1.3 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from flask->jupyter_dash) (8.1.8)
Requirement already satisfied: blinker>=1.6.2 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from flask->jupyter_dash) (1.9.0)
Requirement already satisfied: comm>=0.1.1 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ipykernel->jupyter_dash) (0.2.2)
Requirement already satisfied: debugpy>=1.6.5 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ipykernel->jupyter_dash) (1.8.14)
Requirement already satisfied: jupyter-client>=6.1.12 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ipykernel->jupyter_dash) (8.6.3)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ipykernel->jupyter_dash) (5.7.2)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ipykernel->jupyter_dash) (0.1.7)
Requirement already satisfied: packaging in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ipykernel->jupyter_dash) (25.0)
Requirement already satisfied: psutil in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ipykernel->jupyter_dash) (7.0.0)
Requirement already satisfied: pyzmq>=24 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ipykernel->jupyter_dash) (26.4.0)
Requirement already satisfied: tornado>=6.1 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ipykernel->jupyter_dash) (6.4.2)
Requirement already satisfied: traitlets>=5.4.0 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ipykernel->jupyter_dash) (5.14.3)
Requirement already satisfied: colorama in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ipython->jupyter_dash) (0.4.6)
Requirement already satisfied: decorator in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ipython->jupyter_dash) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ipython->jupyter_dash) (1.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ipython->jupyter_dash) (0.19.2)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ipython->jupyter_dash) (3.0.51)
Requirement already satisfied: pygments>=2.4.0 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ipython->jupyter_dash) (2.19.1)
Requirement already satisfied: stack_data in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from ipython->jupyter_dash) (0.6.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests->jupyter_dash) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests->jupyter_dash) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests->jupyter_dash) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests->jupyter_dash) (2025.4.26)
Requirement already satisfied: six>=1.7.0 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from retrying->jupyter_dash) (1.17.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from jedi>=0.16->ipython->jupyter_dash) (0.8.4)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from Jinja2>=3.1.2->flask->jupyter_dash) (3.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from jupyter-client>=6.1.12->ipykernel->jupyter_dash) (2.9.0.post0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel->jupyter_dash) (4.3.7)
Requirement already satisfied: pywin32>=300 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel->jupyter_dash) (310)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from plotly>=5.0.0->dash->jupyter_dash) (1.36.0)
Requirement already satisfied: wcwidth in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython->jupyter_dash) (0.2.13)
Requirement already satisfied: zipp>=3.20 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from importlib-metadata->dash->jupyter_dash) (3.21.0)
Requirement already satisfied: executing>=1.2.0 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from stack_data->ipython->jupyter_dash) (2.2.0)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from stack_data->ipython->jupyter_dash) (3.0.0)
Requirement already satisfied: pure-eval in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from stack_data->ipython->jupyter_dash) (0.2.3)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 25.1
[notice] To update, run: C:\Users\srira\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [3]:
%pip install dash_bootstrap_components

Requirement already satisfied: dash_bootstrap_components in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (2.0.2)
Requirement already satisfied: dash>=3.0.3 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dash_bootstrap_components) (3.0.4)
Requirement already satisfied: Flask<3.1,>=1.0.4 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dash>=3.0.3->dash_bootstrap_components) (3.0.3)
Requirement already satisfied: Werkzeug<3.1 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dash>=3.0.3->dash_bootstrap_components) (3.0.6)
Requirement already satisfied: plotly>=5.0.0 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dash>=3.0.3->dash_bootstrap_components) (6.0.1)
Requirement already satisfied: importlib-metadata in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dash>=3.0.3->dash_bootstrap_components) (8.7.0)
Requirement already satisfied: typing-extensions>=4.1.1 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dash>=3.0.3->dash_bootstrap_components) (4.13.2)
Requirement already satisfied: requests in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dash>=3.0.3->dash_bootstrap_components) (2.32.3)
Requirement already satisfied: retrying in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dash>=3.0.3->dash_bootstrap_components) (1.3.4)
Requirement already satisfied: nest-asyncio in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from dash>=3.0.3->dash_bootstrap_components) (1.6.0)
Requirement already satisfied: setuptools in c:\program files\windowsapps\pythonsoftwarefoundation.python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\lib\site-packages (from dash>=3.0.3->dash_bootstrap_components) (65.5.0)
Requirement already satisfied: Jinja2>=3.1.2 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from Flask<3.1,>=1.0.4->dash>=3.0.3->dash_bootstrap_components) (3.1.6)
Requirement already satisfied: itsdangerous>=2.1.2 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from Flask<3.1,>=1.0.4->dash>=3.0.3->dash_bootstrap_components) (2.2.0)
Requirement already satisfied: click>=8.1.3 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from Flask<3.1,>=1.0.4->dash>=3.0.3->dash_bootstrap_components) (8.1.8)
Requirement already satisfied: blinker>=1.6.2 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from Flask<3.1,>=1.0.4->dash>=3.0.3->dash_bootstrap_components) (1.9.0)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from plotly>=5.0.0->dash>=3.0.3->dash_bootstrap_components) (1.36.0)
Requirement already satisfied: packaging in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from plotly>=5.0.0->dash>=3.0.3->dash_bootstrap_components) (25.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from Werkzeug<3.1->dash>=3.0.3->dash_bootstrap_components) (3.0.2)
Requirement already satisfied: zipp>=3.20 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from importlib-metadata->dash>=3.0.3->dash_bootstrap_components) (3.21.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests->dash>=3.0.3->dash_bootstrap_components) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests->dash>=3.0.3->dash_bootstrap_components) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests->dash>=3.0.3->dash_bootstrap_components) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from requests->dash>=3.0.3->dash_bootstrap_components) (2025.4.26)
Requirement already satisfied: six>=1.7.0 in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from retrying->dash>=3.0.3->dash_bootstrap_components) (1.17.0)
Requirement already satisfied: colorama in c:\users\srira\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from click>=8.1.3->Flask<3.1,>=1.0.4->dash>=3.0.3->dash_bootstrap_components) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 25.1
[notice] To update, run: C:\Users\srira\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [4]:
# Importing necessary libraries
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objs as go
from dash import dcc, html, Input, Output
from jupyter_dash import JupyterDash
import dash_bootstrap_components as dbc

## Data Loading

In [5]:
# Load the dataset
df = pd.read_csv("data/GlobalLandTemperaturesByCountry.csv")
df['dt'] = pd.to_datetime(df['dt'])
df['Year'] = df['dt'].dt.year
df = df[df['Year'] >= 2000]
df.head()

,dt,AverageTemperature,AverageTemperatureUncertainty,Country,Year
3074,2000-01-01,0.197,0.407,Åland,2000
3075,2000-02-01,-0.023,0.399,Åland,2000
3076,2000-03-01,0.615,0.429,Åland,2000
3077,2000-04-01,4.124,0.348,Åland,2000
3078,2000-05-01,8.557,0.447,Åland,2000

## Data Cleaning

In [6]:
# Rename columns for ease
df = df.rename(columns={
    'AverageTemperature': 'AvgTemp',
    'AverageTemperatureUncertainty': 'TempUncertainty'
})

# Drop missing values
df = df.dropna(subset=['AvgTemp', 'Country'])

# Group by Country-Year
df_grouped = df.groupby(['Country', 'Year'])[['AvgTemp', 'TempUncertainty']].mean().reset_index()

df_grouped.head()

       Country  Year    AvgTemp  TempUncertainty
0  Afghanistan  2000  15.497833         0.500667
1  Afghanistan  2001  15.778083         0.539083
2  Afghanistan  2002  15.537667         0.445167
3  Afghanistan  2003  14.916000         0.456667
4  Afghanistan  2004  15.770917         0.482500

## Feature Engineering

In [7]:
# Create rolling temperature averages
df_grouped['RollingTemp'] = df_grouped.groupby('Country')['AvgTemp'].transform(lambda x: x.rolling(window=3, min_periods=1).mean())

## Static Visualizations

In [8]:
# Line plot
fig1 = px.line(df_grouped[df_grouped['Country']=='India'], x='Year', y='AvgTemp', title='Avg Temperature Over Time (India)', template='plotly_dark')
fig1.show(renderer="browser")

# Scatter plot
fig2 = px.scatter(df_grouped, x='AvgTemp', y='TempUncertainty', color='Country', title='Temp vs Uncertainty', template='plotly_dark')
fig2.show(renderer="browser")

# Box plot
fig3 = px.box(df_grouped, x='Country', y='AvgTemp', title='Temperature Distribution per Country', template='plotly_dark')
fig3.show(renderer="browser")

# Bubble chart
fig4 = px.scatter(df_grouped, x='Year', y='AvgTemp', size='TempUncertainty', color='Country', title='Bubble Chart: Temp vs Uncertainty', template='plotly_dark')
fig4.show(renderer="browser")

# Histogram
fig5 = px.histogram(df_grouped, x='AvgTemp', nbins=50, title='Temperature Frequency Distribution', template='plotly_dark')
fig5.show(renderer="browser")

# Choropleth map
fig6 = px.choropleth(df_grouped, locations="Country", locationmode="country names", color="AvgTemp", hover_name="Country", animation_frame="Year", color_continuous_scale=px.colors.sequential.Plasma, title='World Map Avg Temperature')
fig6.show(renderer="browser")

## Interactive Dash Dashboard

In [9]:
# Building JupyterDash App
app = JupyterDash(__name__, external_stylesheets=[dbc.themes.CYBORG])

app.layout = dbc.Container([
    html.H1("Global Climate Change Dashboard", style={'textAlign': 'center', 'marginTop': 20}),
    dbc.Row([
        dbc.Col([
            html.Label("Select Country:"),
            dcc.Dropdown(
                id='country-dropdown',
                options=[{'label': i, 'value': i} for i in df_grouped['Country'].unique()],
                value='India'
            ),
            html.Label("Select Year Range:"),
            dcc.RangeSlider(
                id='year-slider',
                min=df_grouped['Year'].min(),
                max=df_grouped['Year'].max(),
                value=[2000, 2015],
                marks={str(year): str(year) for year in range(2000, 2016, 3)}
            ),
            html.Label("Temperature Range:"),
            dcc.RangeSlider(
                id='temp-slider',
                min=-20,
                max=40,
                value=[0, 30],
                marks={i: f"{i}°C" for i in range(-20, 41, 10)}
            )
        ], width=3),
        dbc.Col([
            dcc.Graph(id='line-plot'),
            dcc.Graph(id='scatter-plot'),
            dcc.Graph(id='box-plot'),
            dcc.Graph(id='histogram-plot'),
            dcc.Graph(id='choropleth-plot')
        ], width=9)
    ])
], fluid=True)

# Callback to update all plots
@app.callback(
    Output('line-plot', 'figure'),
    Output('scatter-plot', 'figure'),
    Output('box-plot', 'figure'),
    Output('histogram-plot', 'figure'),
    Output('choropleth-plot', 'figure'),
    Input('country-dropdown', 'value'),
    Input('year-slider', 'value'),
    Input('temp-slider', 'value')
)
def update_graphs(selected_country, selected_years, temp_range):
    filtered = df_grouped[(df_grouped['Year'] >= selected_years[0]) &
                          (df_grouped['Year'] <= selected_years[1]) &
                          (df_grouped['AvgTemp'] >= temp_range[0]) &
                          (df_grouped['AvgTemp'] <= temp_range[1])]
    
    # Line Chart
    line_fig = px.line(filtered[filtered['Country'] == selected_country], x='Year', y='AvgTemp',
                       title=f'Average Temperature Over Time: {selected_country}', template='plotly_dark')
    
    # Scatter Plot
    scatter_fig = px.scatter(filtered[filtered['Country'] == selected_country], x='Year', y='TempUncertainty',
                             color='AvgTemp', title='Year vs Temp Uncertainty', template='plotly_dark')
    
    # Box Plot
    box_fig = px.box(filtered[filtered['Country'] == selected_country], y='AvgTemp',
                     title='Temperature Distribution', template='plotly_dark')
    
    # Histogram
    hist_fig = px.histogram(filtered[filtered['Country'] == selected_country], x='AvgTemp',
                            nbins=30, title='Temperature Frequency Distribution', template='plotly_dark')
    
    # Choropleth Map
    choropleth_fig = px.choropleth(
        filtered, locations="Country", locationmode="country names",
        color="AvgTemp", hover_name="Country",
        animation_frame="Year", color_continuous_scale=px.colors.sequential.Plasma,
        title='World Map of Avg Temperature'
    )
    
    return line_fig, scatter_fig, box_fig, hist_fig, choropleth_fig

# Run app
app.run(mode='external')
#Navigate to http://127.0.0.1:8050/ after this cell to get full view of dashboard

C:\Users\srira\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\dash\dash.py:587: UserWarning:

JupyterDash is deprecated, use Dash instead.
See https://dash.plotly.com/dash-in-jupyter for more details.